name: deploy webpage

on:
  push:
    branches: ["main"]

jobs:
  deploy-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to S3
        run: aws s3 sync . s3://hubertszulc.eu --delete --exclude ".github/*" --exclude ".git/*" --exclude ".gitignore" --exclude "example" --exclude "README.md" --exclude "package.json" --exclude "package-lock.json" --exclude "notes.md" --exclude "node_modules/*" --exclude "design.md" --exclude "scss/*" --exclude "terraform/*"
