name: deploy webpage

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            [ ! -d ~/physiotherapy-webpage ] && git clone git@github.com:${{ github.repository }}.git
            cd ~/physiotherapy-webpage
            git fetch
            git checkout main
            git reset --hard origin/main
            git pull
